services:
  model-downloader:
      image: python:3.11-slim
      command: ["bash", "/app/download_model.sh"]
      environment:
        HUGGINGFACE_HUB_TOKEN: ${HUGGINGFACE_HUB_TOKEN}
      volumes:
        - ./download_model.sh:/app/download_model.sh:ro
        - hf_cache:/root/.cache/huggingface
      restart: "no"
  backend:
    build: .
    container_name: germanai-backend
    ports:
      - "8080:8080"
    environment:
      LANGUAGETOOL_API: http://languagetool:8010/v2/check
      ALLOWED_ORIGINS: "http://localhost:8080,http://10.0.2.2:8080"

      # Keycloak integration variables (for JWT validation only):
      KEYCLOAK_URL_INTERNAL: ${KEYCLOAK_URL_INTERNAL}
      KEYCLOAK_URL_PUBLIC: ${KEYCLOAK_URL_PUBLIC}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}

      # --- Not needed for JWT validation, kept for reference to restore full OAuth2 flow or admin automation ---
      # KEYCLOAK_ADMIN_CLIENT_SECRET: None
      # CALLBACK_URI: vokabelmeister://callback
      HUGGINGFACE_HUB_TOKEN: ${HUGGINGFACE_HUB_TOKEN}
      # LLAMA_GGUF_PATH: ${LLAMA_GGUF_PATH}
      # TRANSFORMERS_MODEL_NAME: ${TRANSFORMERS_MODEL_NAME}
    depends_on:
      - model-downloader
      - languagetool
      - keycloak
    restart: unless-stopped
    volumes:
      - hf_cache:/root/.cache/huggingface

  languagetool:
    image: silviof/docker-languagetool:latest
    container_name: languagetool
    ports:
      - "8081:8010" # Host 8081 -> container 8010 (for browser testing)
    environment:
      - JAVA_OPTS=-Xmx2g
      - LANGUAGETOOL_PORT=8010
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8082:8080" # Host 8082 -> container 8080 (for browser/API testing)
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: unless-stopped

volumes:
  keycloak_data:
  hf_cache:
