version: "3.8"
services:
  fastapi:
    build: .
    ports:
      - "8080:8080"  # Access FastAPI at http://localhost:8080
    depends_on:
      - languagetool
      - libretranslate
    environment:
      - ALLOWED_ORIGINS=http://localhost:8080,http://10.0.2.2:8080
      - LANGUAGETOOL_API=http://languagetool:8010/v2/check
      - TRANSLATE_API=http://libretranslate:5000/translate
    volumes:
      - .:/app       # Optional: enables live code reload if using uvicorn --reload

  languagetool:
    image: silviof/docker-languagetool
    ports:
      - "8081:8010"  # Host 8081 -> container 8010 (for browser testing)
    environment:
      - JAVA_OPTS=-Xmx1g
      - LANGUAGETOOL_PORT=8010

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"  # Host 5000 -> container 5000 (for browser/API testing)
    environment:
      - LT_HOST=0.0.0.0
