version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - languagetool
  languagetool:
    image: silviof/docker-languagetool
    ports:
      - "8081:8010"  # Map container's 8010 to host's 8081
