import os

# Declare this in .env file
LANGUAGETOOL_API = os.getenv("LANGUAGETOOL_API")
OLLAMA_URL = os.environ.get("OLLAMA_URL")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3")
KEYCLOAK_URL_INTERNAL = os.getenv("KEYCLOAK_URL_INTERNAL")
KEYCLOAK_URL_PUBLIC = os.getenv("KEYCLOAK_URL_PUBLIC")
KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM")
KEYCLOAK_CLIENT_ID = os.getenv("KEYCLOAK_CLIENT_ID")
KEYCLOAK_CLIENT_SECRET = os.getenv("KEYCLOAK_CLIENT_SECRET")
# KEYCLOAK_ADMIN_CLIENT_SECRET = os.getenv("KEYCLOAK_ADMIN_CLIENT_SECRET")
# CALLBACK_URI = os.getenv("CALLBACK_URI") # where keycloak should be redirected
