name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Uncomment if you add Python-based tests later
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.11"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag (sanitize ref_name)
        id: vars
        run: |
          SAFE_REF_NAME="${GITHUB_REF_NAME//\//-}"
          echo "safe_tag=$SAFE_REF_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/hemrajchauhan/germanai-backend:latest
            ghcr.io/hemrajchauhan/germanai-backend:${{ steps.vars.outputs.safe_tag }}

      # Uncomment and customize for tests!
      # - name: Run tests
      #   run: |
      #     docker compose up -d
      #     sleep 15
      #     # pytest or other test commands
      #     docker compose down
